[default]
extend-ignore-re = ["helo byd"]

[default.extend-identifiers]


[default.extend-words]
# variation of params
parms = "parms"
# It would be best to ignore the dataset file.
# However, known issue https://github.com/crate-ci/typos/issues/347
# typos cannot ignore specified files when used with pre-commit
# Ancient Egyption God
Ba = "Ba"
